---
galaxy_info:
  role_name: metricebat
  author: Veros Kaplan <verosk@noreply.users.github.com>
  description: Ansible Role for metricebat setup
  company: N/A
  license: MIT
  min_ansible_version: 2.6
  platforms:
    - name: Ubuntu
      versions:
        - bionic
    - name: Debian
      versions:
        - buster
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - system

dependencies: []
