
es_users:
  native:
    packetbeat_push:
      password: '{{ secret_packetbeat_push }}'
      roles:
        - remote_monitoring_agent
        - packetbeat_setup
        - packetbeat_writer
        - packetbeat_monitoring

    metricbeat_collector:
      password: '{{ secret_metricbeat_collector }}'
      roles:
        - remote_monitoring_agent
        - remote_monitoring_collector

    metricbeat_push:
      password: '{{ secret_metricbeat_push }}'
      roles:
        - remote_monitoring_agent

    filebeat_push:
      password: '{{ secret_filebeat_push }}'
      roles:
        - remote_monitoring_agent
        - filebeat_setup
        - filebeat_writer
        - filebeat_monitoring

    auditbeat_push:
      password: '{{ secret_auditbeat_push }}'
      roles:
        - remote_monitoring_agent
        - auditbeat_setup
        - auditbeat_writer
        - auditbeat_monitoring

    logstash:
      password: '{{ secret_logstash }}'
      roles:
        - logstash

  file:
    es_admin:
      password: '{{ es_api_basic_auth_password }}'
      roles:
        - admin

    testuser:
      password: '{{ secret_testuser_password }}'
      roles:
        - power_user
        - user
        - superuser

    kibana_server:
      password: '{{ secret_kibana_password }}'
      roles:
        - kibana_system


es_roles:
  file:
    admin:
      cluster:
        - all
      indices:
        - names: '*'
          privileges:
            - all

    power_user:
      cluster:
        - monitor
        - all
      indices:
        - names: '*'
          privileges:
            - all
      user:
        indices:
          - names: '*'
            privileges:
              - read

  native:
    packetbeat_setup:
      cluster:
        - monitor
        - manage_ilm
      indices:
        - names: packetbeat-*
          privileges:
            - manage
            - write
            - view_index_metadata

    packetbeat_monitoring:
      cluster:
        - monitor
      indices:
        - names: .monitoring-beats-*
          privileges:
            - create_index
            - create_doc

    packetbeat_writer:
      cluster:
        - monitor
        - read_ilm
      indices:
        - names: packetbeat-*
          privileges:
            - create_doc
            - create_index
            - view_index_metadata

    filebeat_setup:
      cluster:
        - monitor
        - manage_ilm
        - manage_ml
      indices:
        - names: filebeat-*
          privileges:
            - manage
            - write
            - read

    filebeat_monitoring:
      cluster:
        - monitor
        - manage_ilm
        - manage_ml
      indices:
        - names: .monitoring-beats-*
          privileges:
            - create_index
            - create_doc

    filebeat_writer:
      cluster:
        - monitor
        - read_ilm
        - cluster:admin/ingest/pipeline/get
      indices:
        - names: .filebeat-*
          privileges:
            - create_index
            - create_doc
            - view_index_metadata
            - manage_follow_index

    auditbeat_setup:
      cluster:
        - monitor
        - manage_ilm
      indices:
        - names: auditbeat-*
          privileges:
            - manage
            - write
            - view_index_metadata

    auditbeat_monitoring:
      cluster:
        - monitor
      indices:
        - names: .monitoring-beats-*
          privileges:
            - create_index
            - create_doc

    auditbeat_writer:
      cluster:
        - monitor
        - read_ilm
      indices:
        - names: auditbeat-*
          privileges:
            - create_doc
            - create_index
            - view_index_metadata


    logstash:
      cluster:
        - manage_index_templates
        - monitor
        - manage_ilm

      indices:
        - names: 'logs-*'
          privileges:
            - write
            - delete
            - create
            - create_index
            - manage
            - manage_ilm
        - names: 'logstash-*'
          privileges:
            - write
            - delete
            - create
            - create_index
            - manage
            - manage_ilm




