# https://github.com/elastic/ansible-elasticsearch/blob/master/docs/ssl-tls-setup.md
es_enable_http_ssl: true
es_enable_transport_ssl: true
es_enable_auto_ssl_configuration: true

# ensure version lock on RedHat
es_version_lock: true
es_version: "7.14.0"

es_ssl_upload: true
es_ssl_key: es_certs/{{ inventory_hostname }}/key.pem
es_ssl_certificate: es_certs/{{ inventory_hostname }}/cert.pem
es_ssl_certificate_authority: es_certs/ca_cert.pem

es_validate_certs: no

es_api_basic_auth_username: es_admin
es_api_basic_auth_password: '{{ secret_es_admin_password }}'

es_api_host: 127.0.0.1
es_api_port: 9200
es_transport_port: 9300
